### ISSUE TITLE
Beta test sur produit MUSCATE

### ISSUE THREAD

**Issue by olivegak971** [olivierhagolle/MAJA2SEN2COR#1]
Le process se déroule bien (voir log) : les fichiers jp2 sont générés pour R10m et R20m. Un fichier MTD_TL.xml est généré mais impossible de l'ouvrir avec SNAP (file unhandled).
Reste à tester : utilisation en entrée de  SEN2AGRI
Une seule erreur pendant le "process of masks" : ERROR 1: NUMPY driver was compiled against GDAL 2.0 but current library version is 2.1

[Convert2Sen2cor_2017-10-17T10:51:10.log](https://github.com/olivierhagolle/MAJA2SEN2COR/files/1391546/Convert2Sen2cor_2017-10-17T10.51.10.log)

**Comment by olivierhagolle** [comment]
Merci Olivier. Ca confirme qu'il faut remplir ce fichier xml (ce qui est très pénible à faire...)
Ce n'est pas fait pour aller en entrée de Sen2Agri, ça m'étonnerait que ça fonctionne...

Amitiés,
Olivier

**Comment by resnow92** [comment]
Bonjour, j'ai réussis à faire tourner le process. Il semblerait que le script se déroule jusqu'à la fin et le dossier contenant mon image est créé, ainsi que le fichier xml. Comme les commentaires ont pu le mentionner, ce xml ne peut être lu par SNAP.
Est ce que des améliorations ont été faites pour que le fichier xml soit compatible avec la lecture sur SNAP ? 
J'ai essayé de modifier le xml manuellement et je peux désormais l'ouvrir sur SNAP seulement les bandes des l'image n'apparaissent pas. J'ai uniquement les bandes contenant les view et sun azimuth. Ais-je fais une erreur au niveau de la modification du fichier xml ou est-ce que le script python de conversion s'est mal déroulé quelque part ?

Merci pour votre aide.

**Comment by CDesj** [comment]
Bonjour resnow92, 
Olivier vient de comiter la dernière version du convertisseur sur le github.
Le convertisseur fonctionne maintenant sous Windows, ce qui n'était pas le cas avant d'où l'erreur que tu avais obtenue et mentionnée dans le forum SNAP.
En ce qui concerne l'erreur xml dans SNAP, cette version corrige normalement l'erreur obtenue par olivegak971 citée ci-dessus. 
Nous avons testé avec succès l'ouverture dans SNAP d'un produit converti avec cette nouvelle version du convertisseur.
Si tu as toujours des difficultés avec cette version, n'hésites pas à revenir vers nous.

**Comment by resnow92** [comment]
Bonjour,

Merci pour votre réponse. En effet je suis passée sur un machine virtuelle Linux pour utiliser l’outil et cela a fonctionné. J’ai pu ouvrir l’image sur SNAP sans problème. Un petit détail m’a quand même interpellé, en observant l’histogramme des bandes de l’image, il semblerait que les valeurs de réflectance ne soient pas correctes. J’ai trouvé la relation linéaire suivante afin de retourner aux valeurs « normales » :
10 000x -32 770

Merci en tout cas pour cette nouvelle version et pour votre retour,

Bien cordialement

**Comment by CDesj** [comment]
Nous sommes en train de regarder les valeurs de réflectances anormales. 
Comment en êtes-vous arrivé à la valeur de 10 000x -32 770 ?

**Comment by resnow92** [comment]
En insérant sur Excel la valeur minimum et maximum d’une bande L2A Muscate et la valeur minimum et maximum de la même bande L2A Muscate convertie avec l’outil (les min et max sont obtenus avec l’outil Analysis --> Statistic de SNAP). J’ai ensuite tracé un nuage de points avec ces 4 valeurs et affiché l’équation de la droite. Cette relation semble être la même pour toutes les bandes.
Je viens de refaire le test à l’instant et vous trouverez une capture d’écran du résultat en pièce jointe. J’obtiens 32 768 au lieu de 32 770 que j’avais hier, je ne peux pas expliquer cette différence. Dans tous les cas, si j’applique cette relation à toutes les bandes de l’image convertie et en prenant la valeur absolue, j’obtiens quelque chose de cohérent.
A tester sur une autre image pour voir si cette relation ne change pas (à quelques dixièmes près).

J’espère avoir pu vous aider.
![capture1](https://user-images.githubusercontent.com/37361708/38615788-36fef502-3d92-11e8-8b03-f1339b0ca2b8.PNG)

**Comment by resnow92** [comment]
J’obtiens les même chiffres (PJ) sur une autre image (même tuile)
[cid:image001.png@01D3D18B.7C58A580]

**Comment by CDesj** [comment]
Bonjour,
Nous avons corrigé le problème observé par resnow92 sur les valeurs de réflectances aberrantes dans la dernière version comitée il y a quelques instants par Olivier.
Pour information, le problème était plus complexe et la règle linéaire décrite par resnow92 ne suffit à corriger le problème et revenir sur les "bonnes valeurs" de réflectance. 
Si vous avez toujours des difficultés avec cette nouvelle version, n'hésitez pas à revenir vers nous.

**Comment by olivegak971** [comment]
Bonjour,
super boulot !!  je vais donc restester tout ça.
Bonne journée

**Comment by resnow92** [comment]
Bonjour, 
merci pour ces corrections apportées. Je n'ai pas encore réussis à le faire fonctionner sur Windows mais cela fonctionne parfaitement sur Linux.
Un grand merci !

**Comment by ffilipponi** [comment]
Dear MAJA2SEN2COR developers,

I am using the MAJA2SEN2COR python script to convert Sentinel-2 Theia L2A products to Sen2Cor format.
I receive some error messages any time the script tries to delete the 'aux.xml' files. This is because such files are not generated during the process (I do not know if it may depend on my GDAL settings).

The errors are given from the 'os.remove()' function, in example:
```
os.remove(s_AOTPath + '.aux.xml')
```
I have successfully edited all the python scripts to deal with missing files, like:
```
if os.path.exists(s_AOTPath + '.aux.xml'):
    os.remove(s_AOTPath + '.aux.xml')
```
I hope you could apply this edits to the master version of the MAJA2SEN2COR, for all the python scripts dealing with the removal of 'aux.xml' files.
Thanks for considering this suggestion, regards

Federico Filipponi

**Comment by CDesj** [comment]
Dear ffilipponi,
Thank for your suggestion.
We have modified the master following your examples.
Do not hesitate to contact us if you have any other question or suggestion.
Best regards,

**Comment by resnow92** [comment]
Bonjour, 

j'ai re nouveau un problème sur Linux. J'utilise maintenant les produits L2A au format MUSCATE, le process se déroule normalement et je n'ai pas d'érreur mais il semble que le xml file ne soit pas lisible par SNAP, du moins pas les bandes de réflectance. Pourtant elle sont correctement créees dans les repertoire R10 et R20 et affichable prises une à une... mais pas via le xml. 

Merci.

**Comment by olivierhagolle** [comment]
Bonjour,
 il y a un thread sur ce sujet sur le STEP forum des toolbox Sentinel. Un plugin a été créé pour importer les produits Theia dans MUSCATE, mais les développeurs ont eu du mal à suivre les évolutions de notre format, et nous ne leur avons pas facilité la tâche avec des bugs par ci par là et des changements dont nous ne les avons pas avertis....
https://forum.step.esa.int/t/snap-plugin-to-import-s2-l2a-products-from-theia/9950

**Comment by resnow92** [comment]
bonjour, merci pour votre réponse.
je ne sais pas si le plugin me sera utile car je chercher à calculer les FCOVER de manière automatique et je ne suis pas sûre de pouvoir lire un format MUSCATE dans un graphe xml SNAP.
Ce que je ne comprend pas c'est que dans les posts précédents il semblait que les problèmes de lecture du xml par SNAP aient été résolus. Est-ce que la mise à jour récente de MAJA est à l'origine du problème ?
l'outil fonctionne mais SNAP ne reconnaît que les bandes view et sun azimuth comme cela a déjà pu être mentionné. J'utilise la dernière version de MAJA et je traite les produits au format MUSCATE.

Merci.

**Comment by olivierhagolle** [comment]
Fermé, report vers le forum de l'outil SNAP (mais effectivement, le changement de format a posé des problèmes)
